Models/UserLoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AttendanceMarking.Models
{
    public class UserLoginViewModel
    {
        [Required]
        public string UserId { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AttendanceMarking.Models;
using System.Web.Security;

namespace AttendanceMarking.Controllers
{
    public class AdminAccountController : Controller
    {
        // GET: AdminAccount
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        //The form's data in Register view is posted to this method. 
        //We have binded the Register View with Register ViewModel, so we can accept object of Register class as parameter.
        //This object contains all the values entered in the form by the user.
        [HttpPost]
        public ActionResult SaveRegisterDetails(AdminDetail registerDetails)
        {
            //We check if the model state is valid or not. We have used DataAnnotation attributes.
            //If any form value fails the DataAnnotation validation the model state becomes invalid.
            if (ModelState.IsValid)
            {
                //create database context using Entity framework 
                using (var databaseContext = new AttendanceMarkingEntities())
                {
                    //If the model state is valid i.e. the form values passed the validation then we are storing the User's details in DB.
                    AdminDetail reglog = new AdminDetail();

                    //Save all details in RegitserUser object

                    reglog.FirstName = registerDetails.FirstName;
                    reglog.LastName = registerDetails.LastName;
                    reglog.Age = registerDetails.Age;
                    reglog.Gender = registerDetails.Gender;
                    reglog.ContactNumber = registerDetails.ContactNumber;
                    reglog.AdminId = registerDetails.AdminId;
                    reglog.Password = registerDetails.Password;

                    if(databaseContext.AdminDetails.Any(x =>x.AdminId == reglog.AdminId))
                    {
                        ViewBag.DuplicateMessage = "AdminId already exist.";
                        return View("SaveRegisterDetails", reglog);
                    }
                    //Calling the SaveDetails method which saves the details.
                    databaseContext.AdminDetails.Add(reglog);
                    databaseContext.SaveChanges();
                }

                ViewBag.Message = registerDetails.FirstName + " " + registerDetails.LastName + " your Details Sucessfully Saved";
                //return View("Register");
                return View("Register");
                return RedirectToAction("Login");
            }
            else
            {

                //If the validation fails, we are returning the model object with errors to the view, which will display the error messages.
                return View("Register", registerDetails);
            }
        }


        public ActionResult Login()
        {
            return View();
        }

        //The login form is posted to this method.
        [HttpPost]
        public ActionResult Login(AdminLoginViewModel model)
        {
            //Checking the state of model passed as parameter.
            if (ModelState.IsValid)
            {

                //Validating the user, whether the user is valid or not.
                var isValidUser = IsValidUser(model);

                //If user is valid & present in database, we are redirecting it to Welcome page.
                if (isValidUser != null)
                {
                    FormsAuthentication.SetAuthCookie(model.AdminId, false);
                    return RedirectToAction("Index");
                }
                else
                {
                    //If the username and password combination is not present in DB then error message is shown.
                    ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                    return View();
                }
            }
            else
            {
                //If model state is not valid, the model with error message is returned to the View.
                return View(model);
            }
        }

        //function to check if User is valid or not
        public AdminDetail IsValidUser(AdminLoginViewModel model)
        {
            using (var dataContext = new AttendanceMarkingEntities1())
            {
                //Retireving the user details from DB based on username and password enetered by user.
                AdminDetail user = dataContext.AdminDetails.Where(query => query.AdminId.Equals(model.AdminId) && query.Password.Equals(model.Password)).SingleOrDefault();
                //If user is present, then true is returned.
                if (user == null)
                    return null;
                //If user is not present false is returned.
                else
                    return user;
            }
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AttendanceMarking.Models;
using System.Web.Security;

namespace AttendanceMarking.Controllers
{
    public class UserAccountController : Controller
    {
        // GET: UserAccount
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserRegister()
        {
            return View();
        }

        //The form's data in Register view is posted to this method. 
        //We have binded the Register View with Register ViewModel, so we can accept object of Register class as parameter.
        //This object contains all the values entered in the form by the user.
        [HttpPost]
        public ActionResult SaveRegisterDetails(UserDetail registerDetails)
        {
            //We check if the model state is valid or not. We have used DataAnnotation attributes.
            //If any form value fails the DataAnnotation validation the model state becomes invalid.
            if (ModelState.IsValid)
            {
                //create database context using Entity framework 
                using (var databaseContext = new Attendance_MarkingEntities())
                {
                    //If the model state is valid i.e. the form values passed the validation then we are storing the User's details in DB.
                    UserDetail reglog = new UserDetail();

                    //Save all details in RegitserUser object

                    reglog.FirstName = registerDetails.FirstName;
                    reglog.LastName = registerDetails.LastName;
                    reglog.Age = registerDetails.Age;
                    reglog.Gender = registerDetails.Gender;
                    reglog.ContactNumber = registerDetails.ContactNumber;
                    reglog.UserId = registerDetails.UserId;
                    reglog.Password = registerDetails.Password;


                    //Calling the SaveDetails method which saves the details.
                    databaseContext.UserDetails.Add(reglog);
                    databaseContext.SaveChanges();
                }

                ViewBag.Message = registerDetails.FirstName + " " + registerDetails.LastName + " your Details Sucessfully Saved";
                //return View("Register");
                return View("UserRegister");
                
            }
            else
            {

                //If the validation fails, we are returning the model object with errors to the view, which will display the error messages.
                return View("UserRegister", registerDetails);
            }
        }


        public ActionResult UserLogin()
        {
            return View();
        }

        //The login form is posted to this method.
        [HttpPost]
        public ActionResult UserLogin(UserLoginViewModel model)
        {
            //Checking the state of model passed as parameter.
            if (ModelState.IsValid)
            {

                //Validating the user, whether the user is valid or not.
                var isValidUser = IsValidUser(model);

                //If user is valid & present in database, we are redirecting it to Welcome page.
                if (isValidUser != null)
                {
                    FormsAuthentication.SetAuthCookie(model.UserId, false);
                    return RedirectToAction("Index");
                }
                else
                {
                    //If the username and password combination is not present in DB then error message is shown.
                    ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                    return View();
                }
            }
            else
            {
                //If model state is not valid, the model with error message is returned to the View.
                return View(model);
            }
        }

        

        //function to check if User is valid or not
        public UserDetail IsValidUser(UserLoginViewModel model)
        {
            using (var dataContext = new Attendance_MarkingEntities())
            {
                //Retireving the user details from DB based on username and password enetered by user.
                UserDetail user = dataContext.UserDetails.Where(query => query.UserId.Equals(model.UserId) && query.Password.Equals(model.Password)).SingleOrDefault();
                //If user is present, then true is returned.
                if (user == null)
                    return null;
                //If user is not present false is returned.
                else
                    return user;
            }
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("Index");
        }
    }
}

Views/UserAccount/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Index_LayoutPage1.cshtml";
}


	<h1>Attendance Marking</h1>
@if (Request.IsAuthenticated)
{

    <span>Welcome @Html.Encode(User.Identity.Name) </span>
}
else
{

    @Html.ActionLink("ADMIN", "Register", "AdminAccount")<br />

    @Html.ActionLink("USER", "UserRegister", "UserAccount")
}

Views/UserAccount/UserLogin.cshtml
@model AttendanceMarking.Models.UserLoginViewModel
@{
    ViewBag.Title = "UserLogin";
    Layout = "~/Views/Shared/Login_LayoutPage1.cshtml";
}

<h2>UserLogin</h2>

<div>
    @using (Html.BeginForm("UserLogin", "UserAccount"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="row">
            <!--Show details are saved successfully message-->
            <div class="col-lg-12">@ViewBag.Message</div>
        </div><br />

        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.UserId)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.UserId, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.Password)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.Password, new { @class = "form-control", type = "Password" })</div>
        </div><br />
        <input type="submit" value="Login" class="btn btn-primary" />
    }

</div>

Views/UserAccount/UserRegister.cshtml
@model AttendanceMarking.Models.UserDetail
@{
    ViewBag.Title = "UserRegister";
    Layout = "~/Views/Shared/UserRegister_LayoutPage1.cshtml";
}

<h2>UserRegister</h2>

<div>
    @using (Html.BeginForm("SaveRegisterDetails", "UserAccount"))
    {
        <div style="color:red;">@Html.ValidationSummary()</div>
        <div class="row">
            <!--Show details are saved successfully message-->
            <div class="col-lg-12">@ViewBag.Message</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.FirstName)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.FirstName, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.LastName)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.LastName, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.Age)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.Age, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.Gender)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.Gender, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.ContactNumber)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.ContactNumber, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.UserId)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.UserId, new { @class = "form-control" })</div>
        </div><br />
        <div class="row">
            <div class="col-lg-2">@Html.LabelFor(a => a.Password)</div>
            <div class="col-lg-10">@Html.TextBoxFor(a => a.Password, new { @class = "form-control", type = "Password" })</div>
        </div><br />
        <input type="submit" value="Register" class="btn btn-primary" /><br />
    }

</div>